name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "./go.mod"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -json -coverpkg=./... -coverprofile=coverage.out ./... > test-report.json

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.ENTUR_SONAR_PASSWORD }}

  release-please:
    needs: [build]
    permissions:
      contents: write
      pull-requests: write
      issues: write
    uses: entur/gha-meta/.github/workflows/release.yml@v1
    with:
      release_type: go
